# MNIST_DIGIT_RECOGNIZER

In [1]:
#Importing the required library..##
from PIL import Image
import mnist
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [2]:
#Training Set
x_train = mnist.train_images()
y_train = mnist.train_labels()

#Testing Set
x_test = mnist.test_images()
y_test = mnist.test_labels()

In [3]:
#Checking the shape of training and testing data
print('training shape', x_train.shape)
print('testing shape', x_test.shape)

training shape (60000, 28, 28)
testing shape (10000, 28, 28)


In [4]:
#changing the shape of training and testing datasets for Neural Networks
x_train = x_train.reshape((-1, 28*28))
x_test = x_test.reshape(-1, 28*28)

In [5]:
#Now limiting the value of arrays between 0 to 1
x_train = (x_train/256)
x_test = (x_test/256)

In [6]:
model = MLPClassifier(solver = 'adam', activation = 'relu', hidden_layer_sizes =(64, 64) )

model.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [7]:
#Predicting the value of the model on the test data
predictions = model.predict(x_test)

In [8]:
#finding the accuracy of the given model
accuracy = confusion_matrix(y_test, predictions)

In [9]:
print(accuracy)

[[ 971    1    1    0    0    0    2    1    3    1]
 [   0 1126    3    1    0    1    0    1    3    0]
 [   2    1 1013    4    1    2    0    4    5    0]
 [   0    0    5  989    0    1    0    3    3    9]
 [   2    0    1    1  957    0    6    2    1   12]
 [   3    1    0    8    1  869    3    1    5    1]
 [   3    4    4    1    4    8  933    0    1    0]
 [   2    1   10    2    1    0    0 1003    3    6]
 [   7    0    3    4    2    3    1    4  946    4]
 [   3    2    1    4    6    4    0    5    2  982]]


In [10]:
#defining the fuction such that to find the sum of diagonals upon the other elements
def result(cm):
    diagonal = cm.trace()
    elements = cm.sum()
    return diagonal / elements

In [11]:
print("Accuracy of the model is: ", result(accuracy))

Accuracy of the model is:  0.9789


In [12]:
#converting the RGB pictures to gray scale in the form of list
import cv2

image = cv2.imread('five_s.png')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray_image = gray_image.reshape(-1, 28*28)
gray_image_l = gray_image[0].tolist()


In [13]:
#Changing the mode of picture according to the model
data = gray_image_l
for i in range(len(data)):
    data[i] = 255 - data[i]
print()


In [14]:
#Limiting the model between 0 and 1
r_data =np.array(data)/256

In [15]:
#Finding the prediction on the real data
answer = model.predict([r_data])

In [17]:
print("The Prediction of the given model is: ", answer[0])

The Prediction of the given model is:  5
